name: Build and Deploy Flask app to Azure Web App

on:
  push:
    branches:
      - main  # This is the branch to watch for changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Zip and Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'niels-webapp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
